env:
  node: true
  es2021: true
  jest: true
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - plugin:prettier/recommended
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - "@typescript-eslint"
  - prettier
rules:
  prettier/prettier: error

  camelcase:
    - error
    - properties: "always"
  eqeqeq:
    - error
    - always
  no-eval:
    - error
  no-implied-eval:
    - error
  curly:
    - error
    - all
  no-fallthrough:
    - error
  no-undef:
    - error
  no-use-before-define:
    - error
    - functions: false
      classes: true
      variables: true
  max-len:
    - "warn"
    - {
        code: 120,
        comments: 120,
        ignoreComments: false,
        ignoreTrailingComments: true,
        ignoreUrls: true,
        ignoreStrings: true,
        ignoreTemplateLiterals: true,
        ignoreRegExpLiterals: true,
        tabWidth: 2,
      }
