name: CI/CD Pipeline

on:
  pull_request:
  push:

jobs:
  lint-and-tests:
    name: Lint, Prettier Check, and Unit Tests
    runs-on: ubuntu-latest

    steps:
      # Clone the source code from the repository into the runtime environment (checkout)
      - name: Checkout code
        uses: actions/checkout@v2

      # Config environment
      - name: Set up Node.js 20.11.0
        uses: actions/setup-node@v3
        with:
          node-version: 20.11.0

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Check lint and prettier
      - name: Lint & Prettier checks
        run: npm run lint

      # Run unit tests
      - name: Run Unit Tests
        run: npm test -- --testPathIgnorePatterns=integration