name: CI/CD Pipeline

on:
  pull_request:
  push:

jobs:
  lint-and-unit-tests:
    name: Lint, Prettier Check, and Unit Tests
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.11.0]

    steps:
      # Clone the source code from the repository into the runtime environment (checkout)
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Config environment
      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
          cache-dependency-path: "./package.json"

      # Install dependencies
      - name: Install dependencies
        run: npm i --legacy-peer-deps

      # Check lint and prettier
      - name: Lint & Prettier checks
        run: npm run lint

      # Run unit tests
      - name: Run Unit Tests
        run: npm test -- --testPathIgnorePatterns=integration

  integration-tests:
    name: Check Integration Tests
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: user
          POSTGRES_PASSWORD: password
          POSTGRES_DB: test_db
        options: >-
          --health-cmd="pg_isready -U user -d test_db"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5
        ports:
          - 5432:5432

    steps:
      # Clone the source code from the repository into the runtime environment (checkout)
      - name: Checkout code
        uses: actions/checkout@v2

      # Config environment
      - name: Set up Node.js 20.11.0
        uses: actions/setup-node@v3
        with:
          node-version: 20.11.0

      # Wait for the database service to be healthy
      - name: Wait for PostgreSQL to be ready
        run: until pg_isready -h localhost -p 5432 -U user -d test_db; do echo waiting for postgres; sleep 5; done

      # Set up environment variables for Prisma
      - name: Set up database URL
        run: echo "DATABASE_URL=postgresql://user:password@localhost:5432/test_db?schema=public" >> $GITHUB_ENV

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Run migrations or reset the database if needed
      - name: Run Prisma migrations
        run: npx prisma migrate deploy

      #TODO: Quizas convenga que haga 2 scripts diferentes en package.json donde defino las regex y aca correr los 2 comandos por separado para unit esrt y el otro para integration.
      # Run integration tests
      - name: Run Integration Tests
        run: TEST_ENV=integration npm test -- --testPathPattern=".*\\.integration\\.test\\.ts$"